apiVersion: v1
kind: Secret
metadata:
  name: coffeeshop-secrets
type: Opaque
stringData:
  # Postgres
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "P@ssw0rd"
  # RabbitMQ
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  # URLs
  PG_URL: "postgres://postgres:P@ssw0rd@postgres:5432/postgres"
  PG_URL_SSL: "postgres://postgres:P@ssw0rd@postgres:5432/postgres?sslmode=disable"
  PG_DSN_URL: "host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"