# Step 1: Modules
FROM golang:1.25-alpine AS modules
WORKDIR /modules
COPY go.mod go.sum ./
RUN go mod download

# Step 2: Builder
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY --from=modules /go/pkg /go/pkg
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/auth

# Step 3: Final
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/app .
COPY --from=builder /app/cmd/auth/config.yml .

EXPOSE 5005
CMD ["./app"]