# Step 1: Modules caching
FROM golang:1.25-alpine AS modules
WORKDIR /modules
COPY go.mod go.sum ./
RUN go mod download

# Step 2: Builder
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY --from=modules /go/pkg /go/pkg
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/app ./cmd/barista

# Step 3: Final
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /bin/app .
COPY --from=builder /app/cmd/barista/config.yml .
COPY --from=builder /app/db/migrations ../../../db/migrations
EXPOSE 8080

CMD ["./app"]